### ISSUE TITLE
Different extinction values

### ISSUE THREAD

**Issue by Shalmalee15** [astropy/SPISEA#49]
Hi. I have a question. Can I use two different extinction values for the same synthetic cluster? Is there any way I can incorporate that in the code? I recently read that some clusters (especially in the Milky Way), part of them are hidden behind the magnitude of extiction and rest of the cluster remains unaffected due to extinction. Is this feasible using SPISEA? Or is it something simple and I am overthinking? 

Thanks so much in advance!

**Comment by jluastro** [comment]
While there isn’t currently a SPISEA cluster object that takes two distinct extinction values, there are a couple of options. There is a “differential reddened” cluster that will take a mean and standard deviation extinction and produce a Gaussian distribution of extinctions. Or you can make two separate clusters and give them different extinctions and then append the astropy tables that contain the stars. Hope that helps!

**Comment by Shalmalee15** [comment]
That's fantastic. I will try both options. Thanks for the suggestions.
