### ISSUE TITLE
Adding errors to the model

### ISSUE THREAD

**Issue by Shalmalee15** [astropy/SPISEA#58]
Hi, is there any way I can add observational errors in Spisea models? 
Or maybe get error values at the certain evolutionary stage of a cluster from my existing model? 

Currently, I am getting these columns: 

mass | isMultiple | systemMass | Teff | L | logg | isWR | mass_current | phase | m_hst_f336w | m_hst_f475w | m_hst_f814w | N_companions

Sorry if it's a stupid or repeated question, just want to make sure about the method I am implementing in my paper. Thanks in advance!

**Comment by mwhosek** [comment]
Hi Shalmalee,

I'm assuming you want to add observational errors to the synthetic photometry? SPISEA doesn't have the functionality to add observational errors "under the hood", but it is something you can add to the model clusters after you produce them. For example, if you want to add observational errors to the F475W photometry for a given SPISEA star, you could calculate the "observed" F475W mag as a random draw from a Gaussian distribution with a mean equal to the predicted F475W mag from the SPISEA model (the "true" value) and a standard deviation equal to whatever your observational error is. This introduces a scatter to the photometric sequence of the cluster that simulates effect of observational errors. This is only one approach; what method you adopt depends on what analysis you are doing.

Hope this helps,
Matt
