### ISSUE TITLE
Open Star Cluster

### ISSUE THREAD

**Issue by matg41** [astropy/SPISEA#62]
Hello
Sorry for my basic question, but is there any way to create an open star cluster using SPISEA package?
Thanks

**Comment by mwhosek** [comment]
Hi,

Yes, you can simulate the stellar population of an open cluster using SPISEA. Check out our [Quick Start Guide](https://github.com/astropy/SPISEA/blob/main/docs/Quick_Start_Make_Cluster.ipynb), which gives an example of how to generate a star cluster population. 

Hope this helps,
Matt

**Comment by matg41** [comment]
Hello again and thanks for your response.
I am trying to simulate the Open Star Clusters and need astrometric parameters (i.e. parallax, Right Ascension). Is your library able to generate such a simulation?

Best Regards.

**Comment by mwhosek** [comment]
Hi,

No, SPISEA doesn't currently assign positions (e.g. RA, DEC) or parallax to the stellar population it produces. However, this can be done by the user afterwards: once SPISEA to generate the table of stars that is in the cluster, you can assign positions + parallax values to each individual star system however you wish. 

-Matt
